import { ProjectConfig } from '../types';
import { generateNextJS, generateReact, generateHTML } from './frontend';
import { generateExpress } from './backend/express';
import { generateNestJS } from './backend/nestjs';
import { generateFastAPI } from './backend/fastapi';
import { generateCDK } from './backend/cdk';
import { generateSAM } from './backend/sam';
import { RECOMMENDED_NODE, ROOT_DEV_DEPENDENCIES } from './shared/constants';
import { writeNodeVersionFiles, withEngines } from './shared/node-config';
import { writeRenovateConfig } from './shared/renovate';
import { ecsDeployWorkflowSteps } from './shared/ecs';
import {
  ciCommand,
  ciInstallWorkspace,
  ciSetupExtraSteps,
  installCommand,
  nodeSetupCache,
  packageManagerLabel,
  packageManagerVersionField,
  rootDevScript,
  workspacesRun,
  workspaceRun,
} from './shared/package-manager';
import { storageLabel, writePnpmWorkspace } from './shared/project-docs';
import {
  e2eDevDependencies,
  performanceDevDependencies,
  rootTestScripts,
  writeRootTestTooling,
} from './shared/test-suites';
import fs from 'fs-extra';
import path from 'path';
export async function generateFrontend(projectPath: string, config: ProjectConfig): Promise<void> {
  const frontendPath = path.join(projectPath, 'frontend');
  await fs.ensureDir(frontendPath);

  switch (config.frontend) {
    case 'nextjs':
      await generateNextJS(frontendPath, config);
      break;
    case 'react':
      await generateReact(frontendPath, config);
      break;
    case 'html':
      await generateHTML(frontendPath, config);
      break;
  }
}

export async function generateBackend(projectPath: string, config: ProjectConfig): Promise<void> {
  const backendPath = path.join(projectPath, 'backend');
  await fs.ensureDir(backendPath);

  switch (config.backend) {
    case 'express':
      await generateExpress(backendPath, config);
      break;
    case 'nest':
      await generateNestJS(backendPath, config);
      break;
    case 'fastapi':
      await generateFastAPI(backendPath, config);
      break;
    case 'cdk':
      await generateCDK(backendPath, config);
      break;
    case 'sam':
      await generateSAM(backendPath, config);
      break;
  }
}

export async function generateMonorepoConfig(projectPath: string, config: ProjectConfig): Promise<void> {
  const pmField = packageManagerVersionField(config.packageManager);
  const testScripts = rootTestScripts(config);
  const rootDevDeps = {
    ...ROOT_DEV_DEPENDENCIES,
    ...e2eDevDependencies(config),
    ...performanceDevDependencies(config),
  };
  const rootPackageJson = withEngines({
    name: config.projectName,
    version: '1.0.0',
    private: true,
    workspaces: ['frontend', 'backend'],
    ...(pmField ? { packageManager: pmField } : {}),
    scripts: {
      dev: rootDevScript(config.packageManager, config.projectName),
      build: workspacesRun(config.packageManager, 'build'),
      lint: workspacesRun(config.packageManager, 'lint'),
      ...testScripts,
    },
    devDependencies: rootDevDeps,
  });

  await fs.writeJSON(path.join(projectPath, 'package.json'), rootPackageJson, { spaces: 2 });
  await writeNodeVersionFiles(projectPath);
  await writeRootTestTooling(projectPath, config);
  if (config.packageManager === 'pnpm') {
    await writePnpmWorkspace(projectPath);
  }
}
export async function generateRootFiles(projectPath: string, config: ProjectConfig): Promise<void> {
  const backendLabel =
    config.backend === 'express'
      ? 'Express.js'
      : config.backend === 'nest'
        ? 'NestJS'
        : config.backend === 'fastapi'
          ? 'FastAPI'
          : config.backend === 'cdk'
            ? 'AWS CDK'
            : 'AWS SAM';

  const deploymentLabel =
    config.deploymentStrategy === 'ecs'
      ? 'AWS ECS (Fargate)'
      : config.backend === 'cdk' || config.backend === 'sam'
        ? 'AWS native'
        : 'Render / PaaS';

  const readme = `# ${config.projectName}

Monorepo scaffold generated by [projects-init-cli](https://github.com/MacAndersonUche/Projects-Init-CLI).

## Structure

\`\`\`text
${config.projectName}/
├── frontend/          # ${config.frontend === 'nextjs' ? 'Next.js' : config.frontend === 'react' ? 'React' : 'HTML'} + Tailwind
├── backend/           # ${backendLabel}
├── docs/              # Project documentation (see backend/docs for API spec)
├── .nvmrc             # Node.js ${RECOMMENDED_NODE} LTS
├── renovate.json      # Automated dependency updates
└── .github/workflows/ # CI/CD
\`\`\`

## Prerequisites

- **Node.js ${RECOMMENDED_NODE} LTS** (see \`.nvmrc\`)
- ${packageManagerLabel(config.packageManager)} (workspaces monorepo)

\`\`\`bash
nvm use   # or: fnm use / volta install node@${RECOMMENDED_NODE}
node -v   # should print v${RECOMMENDED_NODE}.x
\`\`\`

## Getting started

\`\`\`bash
${installCommand(config.packageManager)}
${config.packageManager} run dev
\`\`\`

- Frontend: http://localhost:5173 (Vite) or framework default port
- Backend: http://localhost:3001
- Health: http://localhost:3001/health

## Tech stack

| Layer | Choice |
| --- | --- |
| Frontend | ${config.frontend === 'nextjs' ? 'Next.js' : config.frontend === 'react' ? 'React' : 'HTML'} + Tailwind |
| Backend | ${backendLabel} |
| Storage | ${storageLabel(config)} |
${config.databaseType ? `| Database | ${config.databaseType === 'sql' ? 'SQL' : config.nosqlOption === 'mongodb' ? 'MongoDB' : 'NoSQL'} |\n` : ''}${config.sqlOption ? `| ORM | ${config.sqlOption === 'prisma' ? 'Prisma' : config.sqlOption === 'sequelize' ? 'Sequelize' : 'Raw SQL'} |\n` : ''}${config.apiType ? `| API | ${config.apiType === 'rest' ? 'REST + OpenAPI' : 'GraphQL'} |\n` : ''}| Deployment | ${deploymentLabel} |

## Documentation

- [\`docs/CONTRIBUTING.md\`](docs/CONTRIBUTING.md) — development workflow
- [\`docs/DEPLOYMENT.md\`](docs/DEPLOYMENT.md) — deployment guide
${config.apiType === 'rest' ? `- [\`backend/docs/openapi.yaml\`](backend/docs/openapi.yaml) — OpenAPI 3.1 specification\n` : ''}
## Scripts

| Command | Description |
| --- | --- |
| \`${config.packageManager} run dev\` | Start frontend + backend |
| \`${config.packageManager} run build\` | Build all workspaces |
| \`${config.packageManager} test\` | Run tests in all workspaces |

## Dependency updates

[Renovate](https://docs.renovatebot.com/) is configured via \`renovate.json\`. Enable the Renovate GitHub App on this repository for automated PRs.
`;

  await fs.writeFile(path.join(projectPath, 'README.md'), readme);

  const docsPath = path.join(projectPath, 'docs');
  await fs.ensureDir(docsPath);

  await fs.writeFile(
    path.join(docsPath, 'CONTRIBUTING.md'),
    `# Contributing

1. Use Node.js ${RECOMMENDED_NODE} (\`nvm use\`)
2. \`${installCommand(config.packageManager)}\` from the repo root (do not add a custom \`install\` lifecycle script)
3. Create a feature branch
4. \`${config.packageManager} test\` and \`${config.packageManager} run build\` before opening a PR
`
  );

  const deploymentDoc =
    config.deploymentStrategy === 'ecs'
      ? `# Deployment

## AWS ECS (selected)

See [\`backend/deploy/ecs/README.md\`](../backend/deploy/ecs/README.md) for Docker build, ECR push, and task definition steps.

GitHub Actions workflow \`.github/workflows/deploy.yml\` includes an ECS deploy job when secrets are configured:

- \`AWS_ACCESS_KEY_ID\`, \`AWS_SECRET_ACCESS_KEY\`, \`AWS_REGION\`
- \`ECR_REPOSITORY\`, \`ECS_CLUSTER\`, \`ECS_SERVICE\`
`
      : `# Deployment

## Render / PaaS (selected)

\`backend/render.yaml\` and \`frontend/render.yaml\` contain starter service definitions.

Connect this repository to Render or deploy manually using the included build/start commands.
`;

  await fs.writeFile(path.join(docsPath, 'DEPLOYMENT.md'), deploymentDoc);

  const gitignore = `node_modules/
dist/
build/
coverage/
.env
.env.local
.env.*.local
*.log
.DS_Store
.idea/
.vscode/
*.pyc
__pycache__/
.venv/
venv/
cdk.out/
.sam/
data/
*.db
*.sqlite
*.sqlite3
`;

  await fs.writeFile(path.join(projectPath, '.gitignore'), gitignore);

  await writeRenovateConfig(projectPath);
  await generateCICD(projectPath, config);
}
async function generateCICD(projectPath: string, config: ProjectConfig): Promise<void> {
  const workflowsPath = path.join(projectPath, '.github', 'workflows');
  await fs.ensureDir(workflowsPath);

  const pm = config.packageManager;
  const cache = nodeSetupCache(pm);
  const ciInstall = ciCommand(pm);
  const ciExtra = ciSetupExtraSteps(pm);
  const testFrontend = workspaceRun(pm, 'test', config.projectName, 'frontend');
  const testBackend = workspaceRun(pm, 'test', config.projectName, 'backend');
  const buildFrontend = workspaceRun(pm, 'build', config.projectName, 'frontend');
  const buildBackend = workspaceRun(pm, 'build', config.projectName, 'backend');
  const lintAll = workspacesRun(pm, 'lint');

  // Main CI workflow
  const ciWorkflow = `name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [${RECOMMENDED_NODE}.x]

    steps:
    - uses: actions/checkout@v4
${ciExtra}
    - name: Use Node.js \${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: \${{ matrix.node-version }}
        cache: '${cache}'

    - name: Install dependencies
      run: ${ciInstall}

    - name: Run frontend tests
      run: ${testFrontend}
      continue-on-error: ${config.frontend === 'html' ? 'true' : 'false'}

    - name: Run backend tests
      run: ${testBackend}
      continue-on-error: ${config.backend === 'fastapi' || config.backend === 'cdk' || config.backend === 'sam' ? 'true' : 'false'}

    - name: Build frontend
      run: ${buildFrontend}
      continue-on-error: ${config.frontend === 'html' ? 'true' : 'false'}

    - name: Build backend
      run: ${buildBackend}
      continue-on-error: ${config.backend === 'fastapi' || config.backend === 'cdk' || config.backend === 'sam' ? 'true' : 'false'}

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
${ciExtra}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '${RECOMMENDED_NODE}.x'
        cache: '${cache}'

    - name: Install dependencies
      run: ${ciInstall}

    - name: Run linter
      run: ${lintAll}
      continue-on-error: true
`;

  await fs.writeFile(path.join(workflowsPath, 'ci.yml'), ciWorkflow);

  // Deployment workflow
  const installFrontend = ciInstallWorkspace(pm, 'frontend');
  const installBackend = ciInstallWorkspace(pm, 'backend');
  let deployWorkflow = `name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
    - uses: actions/checkout@v4
${ciExtra}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '${RECOMMENDED_NODE}.x'
        cache: '${cache}'

    - name: Install dependencies
      run: ${installFrontend}

    - name: Build frontend
      run: ${buildFrontend}

    - name: Deploy to Netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: \${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: \${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --dir=frontend/.next --prod
      continue-on-error: true

    - name: Deploy to Render
      run: |
        echo "Deploy to Render by connecting your GitHub repository"
        echo "Or use: render deploy --service=\${{ secrets.RENDER_SERVICE_ID }}"
      continue-on-error: true

  deploy-backend:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
`;

  // Add backend deployment steps based on backend type
  if (config.backend === 'cdk') {
    deployWorkflow += `
    steps:
    - uses: actions/checkout@v4
${ciExtra}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '${RECOMMENDED_NODE}.x'
        cache: '${cache}'

    - name: Install dependencies
      run: ${installBackend}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: \${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Build CDK
      run: ${buildBackend}

    - name: Deploy CDK Stack
      run: |
        cd backend
        npm run cdk deploy -- --require-approval never --all
`;
  } else if (config.backend === 'sam') {
    deployWorkflow += `
    steps:
    - uses: actions/checkout@v4
${ciExtra}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '${RECOMMENDED_NODE}.x'
        cache: '${cache}'

    - name: Install dependencies
      run: ${installBackend}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: \${{ secrets.AWS_REGION || 'us-east-1' }}

    - name: Build SAM application
      run: |
        cd backend
        sam build

    - name: Deploy SAM application
      run: |
        cd backend
        sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
`;
  } else {
    if (config.deploymentStrategy === 'ecs') {
      deployWorkflow += ecsDeployWorkflowSteps(config);
    } else {
      deployWorkflow += `
    steps:
    - uses: actions/checkout@v4
${ciExtra}
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '${RECOMMENDED_NODE}.x'
        cache: '${cache}'

    - name: Install dependencies
      run: ${installBackend}

    - name: Build backend
      run: ${buildBackend}

    - name: Deploy to Render
      run: |
        echo "Deploy to Render by connecting your GitHub repository"
        echo "Or use: render deploy --service=\${{ secrets.RENDER_SERVICE_ID }}"
      continue-on-error: true
`;
    }
  }

  deployWorkflow += `\n`;

  await fs.writeFile(path.join(workflowsPath, 'deploy.yml'), deployWorkflow);
}

